Testing workflows

diff --git a/.github/workflows/spigot-cl.yml b/.github/workflows/spigot-cl.yml
--- a/.github/workflows/spigot-cl.yml
+++ b/.github/workflows/spigot-cl.yml
@@ -11,7 +11,7 @@ jobs:
         spigot-version: ['1.21']
 
     steps:
-      - name: Checkout repository
+      - name: Checkout Repository
         uses: actions/checkout@v4
 
       - name: Set up JDK 22 for Maven Build
@@ -20,7 +20,7 @@ jobs:
           java-version: '22'
           distribution: 'corretto'
 
-      - name: Build with Maven
+      - name: Build With Maven
         run: |
           mvn package
           ls
@@ -31,7 +31,7 @@ jobs:
           mkdir buildtools
           curl -o buildtools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
 
-      - name: Build Spigot server
+      - name: Build Spigot Server
         run: |
           cd buildtools
           java -jar BuildTools.jar --rev ${{ matrix.spigot-version }}
@@ -39,41 +39,41 @@ jobs:
           cp ./spigot-${{ matrix.spigot-version }}.jar ../spigot/spigot.jar
           cd ..
 
-      - name: Copy plugin JAR
+      - name: Copy Plugin JAR
         run: |
           mkdir -p ./spigot/plugins
           cp ./target/controlledplantgrowth*[0-9].jar ./spigot/plugins
 
-      - name: Start Spigot server
+      - name: Start Spigot Server (v${{ matrix.spigot-version }})
         run: |
           cd spigot
           echo "eula=true" > eula.txt
-          java -Xms512M -Xmx1024M -jar spigot.jar nogui &
-          SERVER_PID=$!
-          echo $SERVER_PID > ./serverPid.txt
-          echo "Started Spigot server with PID"
-          echo $SERVER_PID
+          java -Xms512M -Xmx1024M -jar spigot.jar --nogui
 
-      - name: Wait for Spigot server to start
+      - name: Wait for Spigot Server To Start
         run: |
+          timeout=120
+          count=0
           while ! grep -q ")! For help, type" spigot/logs/latest.log; do
+            if [ $count -gt $timeout ]; then
+              echo "Timeout reached. Server did not start within 2 minutes or was aborted."
+              echo "result=failed" >>$GITHUB_OUTPUT
+              exit 1
+            fi
             echo "Server not started yet ... waiting"
             sleep 5
+            count=$((count+5))
           done
 
-      - name: Check if plugin loaded
+      - name: Check if Plugin Loaded
         id: check-plugin
         run: |
           if grep -q "ControlledPlantGrowth is enabled!" spigot/logs/latest.log; then
             echo "Plugin loaded successfully."
             echo "result=passed" >>$GITHUB_OUTPUT
+            exit 0 
           else
             echo "Plugin failed to load."
             echo "result=failed" >>$GITHUB_OUTPUT
+            exit 1
           fi
-
-      - name: Stop Spigot server
-        run: |
-          SERVER_PID=$(cat ./serverPid.txt)
-          kill $SERVER_PID
-          exit 0
